title: Haibo Hao

name: HaiboHao's homepage
description:  I am Haibo Hao. Henry is my English Name, which means great bravery. I completed my bachelor's degree in School of Computer Science at Xi'Dian University of computer science and technology on July 1, 2015.
url: http://haohaibo.github.io

# 自定义post url
permalink: /blog/:title.html
timezone: Asia/Chongqing

# Overriden by GitHub Pages: https://help.github.com/articles/using-jekyll-with-pages#configuring-jekyll
safe: true
lsi: false

markdown: kramdown
kramdown:
    input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
    extensions:
    - autolink
    - footnotes
    - smart
hard_wrap: false
#  use_coderay: true
syntax_highlighter: rouge
#  coderay:
#  coderay_line_numbers:  nil

# White-listed plugins
gems:
  - jekyll-sitemap
